name: Integração Contínua
run-name: ${{ github.actor }} executando CI da branch ${{ github.ref_name }}

on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - dev

jobs:
  validation:
    name: Valida Ambiente da Acions
    runs-on: ubuntu-latest

    steps:
      - name: Configuração do ambiente
        run: echo "Configurações do actions..."
      
      - name: Verficando Rede
        run: echo "Verificando conexão..."

  build:
    name: Faz build do projeto
    runs-on: ubuntu-latest
    needs: validation

    steps:
      - name: Clonando o repositório
        run: echo "Clonando o repositório..."

      - name: Verificanção do NodeJS
        run: echo "Instalar o node, e ver a versão"

      - name: Instala depências do projeto
        run: echo "npm install"

      - name: Build do projeto
        run: echo "npm build"

  test-unid:
    name: Testes de unidade
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Rodando testes de unidade
        run: echo "Ainda não foi implementado nenhum teste de unidade."

  test-integration:
    name: Testes de Integração
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Rodando testes de integração
        run: echo "Ainda não foi implementado nenhum teste de integração."

  resumo:
    name: Resumo do CI
    runs-on: ubuntu-latest
    needs: [test-unid, test-integration]

    steps:
      - name: Resumo da pipeline CI
        run: echo "Resumindo..."
